name: 🚀 Feature Request
description: Proposal for a new feature 

labels:
  - features

# projects:
#   - PixelPulps/5

body:
  - type: textarea
    id: description
    attributes:
      label: Beschreibung